services:
    ethereum_apiconnector:
        class: EtherScan\Resources\ApiConnector
        arguments: ['%etherscan_api_key%']

    ethereum_etherscan:
        class: EtherScan\EtherScan
        arguments: ['@ethereum_apiconnector']