services:
    app_apiconnector:
        class: EtherScan\Resources\ApiConnector
        arguments: ['%etherscan_api_key%']

    app_etherscan:
        class: EtherScan\EtherScan
        arguments: ['@app_apiconnector']